steps:
   - name: 'gcr.io/cloud-builders/git'
     id: 'Get Version'
     args: [fetch, --depth=100]

   - name: 'gcr.io/cloud-builders/gcloud'
     id: 'Get Version'
     entrypoint: 'bash'
     args: 
      - '-c'
      - |
        set -e
        chmod +x ./devops/cloudbuild/scripts/git-version.bash
        ./devops/cloudbuild/scripts/git-version.bash

  