
options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Pull Previous Build
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       docker pull us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder || true
  - id: 'Build Builder'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx build \
            --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder,mode=max \
            --cache-to=type=inline \
            --target builder \
            -t us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder \
            --push .
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Builder
    waitFor:
      - 'Build Builder'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder'

  - name: 'gcr.io/cloud-builders/docker'
    id: Run lint and tests 
    waitFor:
      - 'Build Builder'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'docker run us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder npm run test'

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    waitFor:
      - 'Build Builder'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use &&
        docker buildx build \
            --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder \
            --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images \
            --cache-to=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
            -t us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
            --push .
    timeout: 600s

  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Push
  #   waitFor:
  #     - 'Build'
  #   args:
  #     - 'push'
  #     - 'us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA'

  # - name: gcr.io/cloud-builders/docker
  #   id: Tag Preview Env
  #   waitFor:
  #     - 'Push'
  #   args:
  #     - 'tag'
  #     - 'gcr.io/$PROJECT_ID/gcb-test:$SHORT_SHA'
 

tags: [gcb-test]
timeout: 1800s
