# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:

  - name: 'gcr.io/cloud-builders/docker:20.10.3'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker:20.10.3'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
    waitFor:
      - 'create-builder'

  - name: 'gcr.io/cloud-builders/docker:20.10.3'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'bootstrap'
    waitFor:
      - 'create-builder'
  
  - name: 'gcr.io/cloud-builders/docker:20.10.3'
    args: ['buildx', 'build', '--cache-from', 'type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder', '--cache-to', 'type=inline', '--target', 'builder', '--push', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builde', '.' ]
    id: 'Build Builder'
    waitFor:
      - 'bootstrap'
      
  # - id: 'Build Builder'
  #   name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
    # args:
    #   - '-c'
    #   - |
    #     docker buildx build \
    #         --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder \
    #         --cache-to=type=inline \
    #         --target builder \
    #         --push -t us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder .

  - name: 'gcr.io/cloud-builders/docker'
    id: Run lint and tests 
    waitFor:
      - 'Build Builder'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'docker run us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder npm run test'

  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Build
  #   waitFor:
  #     - 'Build Builder'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       docker buildx create --use &&
  #       docker buildx build \
  #           --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder \
  #           --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images \
  #           --cache-to=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
  #           -t us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
  #           --push .
  #   timeout: 600s
  - name: 'gcr.io/cloud-builders/docker:20.10.3'
    args: ['buildx', 'build', '--cache-from', 'type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder', '--cache-to', 'type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA', '--push', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA', '.' ]
    id: 'Build'
    waitFor:
      - 'Build Builder'
    # args:
    #   - '-c'
    #   - |
    #     docker buildx create --use &&
    #     docker buildx build \
    #         --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/builder \
    #         --cache-from=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images \
    #         --cache-to=type=registry,ref=us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
    #         -t us-east1-docker.pkg.dev/$PROJECT_ID/gcb-test/images:$SHORT_SHA \
    #         --push .
    timeout: 600s

 

tags: [gcb-test]
timeout: 1800s
